### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by MPParsley** [StadGent/node_service_adlib-backend#53]
TypeError: Cannot read property '0' of undefined
    at Object.mapObjectnaam (/opt/app-root/src/src/lib/mappers/utils.js:166:76)
    at StamMapper.doMapping (/opt/app-root/src/src/lib/mappers/stamMapper.js:36:25)
    at StamMapper._transform (/opt/app-root/src/src/lib/mappers/stamMapper.js:11:14)

**Comment by MPParsley** [comment]
https://cjm-web.adlibhosting.com/coghentapi/wwwopac.ashx?output=json&database=objecten&search=priref=550002521

```
          "Object_name": [
            "",
            {
              "object_name": [
                "steelpan"
              ],
              "object_name.authority": [
                ""
              ],
              "object_name.authority.lref": [
                ""
              ],
              "object_name.lref": [
                "550000948"
              ],
              "object_name.notes": [
                ""
              ],
              "object_name.type": [
                ""
              ],
              "object_name.type.lref": [
                ""
              ]
            }
          ],
```
