### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by MPParsley** [StadGent/node_service_adlib-backend#56]
```
TypeError: Cannot read property '0' of undefined
    at TermenMapper.doMapping (/opt/app-root/src/src/lib/mappers/termenMapper.js:381:57)
    at TermenMapper._transform (/opt/app-root/src/src/lib/mappers/termenMapper.js:48:14)
    at TermenMapper.Transform._read (internal/streams/transform.js:205:10)
    at TermenMapper.Transform._write (internal/streams/transform.js:193:12)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at TermenMapper.Writable.write (internal/streams/writable.js:303:10)
    at Adlib.ondata (internal/streams/readable.js:726:22)
    at Adlib.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
```

```
Error mapping priref 530016860
    at TermenMapper.Writable.write (internal/streams/writable.js:303:10)
    at Adlib.ondata (internal/streams/readable.js:726:22)
    at Adlib.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
```

```
          "Related": [
            {
              "relationship.notes": [
                "samenwerking op de The Alfred Collection"
              ],
              "relationship": [
                "Mees, Marie"
              ],
              "relationship.lref": [
                "530016861"
              ]
            }
          ],
```

https://cjm-web.adlibhosting.com/coghentapi/wwwopac.ashx?output=json&database=personen&search=priref=530016860&limit=1

**Comment by MPParsley** [comment]
Fixed in https://github.com/StadGent/node_service_adlib-backend/commit/5542d144b6b345f70f457a4f8abe40f8a228ec40#diff-c5304629bd7cc443ffcfcf211dd76f2710b2c534272193617c755aa73375e5c5R378
