### ISSUE TITLE
TypeError: Cannot read property '0' of undefined - termenMapper.js:380:49

### ISSUE THREAD

**Issue by MPParsley** [StadGent/node_service_adlib-backend#57]
TypeError: Cannot read property '0' of undefined
  | at TermenMapper.doMapping (/opt/app-root/src/src/lib/mappers/termenMapper.js:380:49)
  | at TermenMapper._transform (/opt/app-root/src/src/lib/mappers/termenMapper.js:48:14)
  | at TermenMapper.Transform._read (internal/streams/transform.js:205:10)
  | at TermenMapper.Transform._write (internal/streams/transform.js:193:12)
  | at writeOrBuffer (internal/streams/writable.js:358:12)
  | at TermenMapper.Writable.write (internal/streams/writable.js:303:10)
  | at Adlib.ondata (internal/streams/readable.js:726:22)
  | at Adlib.emit (events.js:400:28)
  | at addChunk (internal/streams/readable.js:290:12)
  | at readableAddChunk (internal/streams/readable.js:265:9)
  | Error mapping priref 670001654

**Comment by MPParsley** [comment]
Fixed in https://github.com/StadGent/node_service_adlib-backend/commit/bbf62347a9bceb92693c00eb267af468c3c6e74a
