### ISSUE TITLE
TypeError: Cannot read property '0' of undefined - termenMapper.js:380:49

### ISSUE THREAD

**Issue by MPParsley** [StadGent/node_service_adlib-backend#58]
TypeError: Cannot read property '0' of undefined
  | at TermenMapper.doMapping (/opt/app-root/src/src/lib/mappers/termenMapper.js:380:49)
  | at processTicksAndRejections (internal/process/task_queues.js:95:5)
  | Error mapping priref 670001655

**Comment by MPParsley** [comment]
Fixed in https://github.com/StadGent/node_service_adlib-backend/commit/bbf62347a9bceb92693c00eb267af468c3c6e74a
